"""Symptom-to-department data supplied for the MedaQueue health assistant."""

SYMPTOM_MAPPINGS = [
    ("fever", "General Medicine", "NORMAL"), ("high fever", "General Medicine", "HIGH"), ("headache", "General Medicine", "NORMAL"), ("body pain", "General Medicine", "NORMAL"), ("weakness", "General Medicine", "NORMAL"), ("fatigue", "General Medicine", "NORMAL"), ("chills", "General Medicine", "NORMAL"), ("dizziness", "General Medicine", "NORMAL"), ("vomiting", "General Medicine", "HIGH"), ("nausea", "General Medicine", "NORMAL"), ("cough", "General Medicine", "NORMAL"), ("cold", "General Medicine", "NORMAL"),
    ("sore throat", "ENT", "NORMAL"), ("ear pain", "ENT", "NORMAL"), ("ear discharge", "ENT", "HIGH"), ("hearing loss", "ENT", "HIGH"), ("nose bleeding", "ENT", "HIGH"), ("sinus pain", "ENT", "NORMAL"), ("hoarseness", "ENT", "NORMAL"), ("difficulty swallowing", "ENT", "HIGH"),
    ("chest pain", "Cardiology", "EMERGENCY"), ("heart palpitations", "Cardiology", "HIGH"), ("high blood pressure", "Cardiology", "HIGH"), ("shortness of breath", "Cardiology", "EMERGENCY"), ("irregular heartbeat", "Cardiology", "HIGH"), ("swollen legs", "Cardiology", "NORMAL"),
    ("fracture", "Orthopedics", "EMERGENCY"), ("joint pain", "Orthopedics", "NORMAL"), ("back pain", "Orthopedics", "NORMAL"), ("neck pain", "Orthopedics", "NORMAL"), ("knee pain", "Orthopedics", "NORMAL"), ("shoulder pain", "Orthopedics", "NORMAL"), ("bone swelling", "Orthopedics", "HIGH"), ("sports injury", "Orthopedics", "HIGH"),
    ("skin rash", "Dermatology", "NORMAL"), ("itching", "Dermatology", "NORMAL"), ("acne", "Dermatology", "LOW"), ("hair loss", "Dermatology", "LOW"), ("eczema", "Dermatology", "NORMAL"), ("skin allergy", "Dermatology", "NORMAL"), ("burn injury", "Dermatology", "HIGH"),
    ("stomach pain", "Gastroenterology", "NORMAL"), ("diarrhea", "Gastroenterology", "NORMAL"), ("constipation", "Gastroenterology", "LOW"), ("blood in stool", "Gastroenterology", "HIGH"), ("acid reflux", "Gastroenterology", "LOW"), ("loss of appetite", "Gastroenterology", "NORMAL"),
    ("tooth pain", "Dental", "NORMAL"), ("bleeding gums", "Dental", "NORMAL"), ("cavities", "Dental", "LOW"), ("pregnancy checkup", "Gynecology", "NORMAL"), ("menstrual pain", "Gynecology", "NORMAL"), ("vaginal bleeding", "Gynecology", "HIGH"), ("breast lump", "Gynecology", "HIGH"), ("infertility", "Gynecology", "NORMAL"),
    ("burning urination", "Urology", "NORMAL"), ("frequent urination", "Urology", "NORMAL"), ("blood in urine", "Urology", "HIGH"), ("kidney pain", "Urology", "HIGH"), ("eye pain", "Ophthalmology", "NORMAL"), ("blurred vision", "Ophthalmology", "HIGH"), ("red eyes", "Ophthalmology", "NORMAL"), ("eye injury", "Ophthalmology", "EMERGENCY"),
    ("anxiety", "Psychiatry", "NORMAL"), ("depression", "Psychiatry", "NORMAL"), ("panic attack", "Psychiatry", "HIGH"), ("insomnia", "Psychiatry", "LOW"), ("memory loss", "Neurology", "HIGH"), ("seizures", "Neurology", "EMERGENCY"), ("tremors", "Neurology", "HIGH"), ("numbness", "Neurology", "HIGH"), ("migraine", "Neurology", "NORMAL"),
    ("persistent cough", "Pulmonology", "HIGH"), ("wheezing", "Pulmonology", "HIGH"), ("asthma attack", "Pulmonology", "EMERGENCY"), ("difficulty breathing", "Pulmonology", "EMERGENCY"), ("excessive thirst", "Endocrinology", "NORMAL"), ("unexplained weight loss", "Endocrinology", "HIGH"), ("high blood sugar", "Endocrinology", "HIGH"), ("thyroid swelling", "Endocrinology", "NORMAL"),
    ("child fever", "Pediatrics", "NORMAL"), ("child cough", "Pediatrics", "NORMAL"), ("child vaccination", "Pediatrics", "LOW"), ("poor growth in child", "Pediatrics", "HIGH"), ("allergic reaction", "Allergy & Immunology", "HIGH"), ("frequent sneezing", "Allergy & Immunology", "LOW"), ("insect bite allergy", "Allergy & Immunology", "NORMAL"),
    ("severe bleeding", "Emergency Medicine", "EMERGENCY"), ("unconsciousness", "Emergency Medicine", "EMERGENCY"), ("stroke symptoms", "Emergency Medicine", "EMERGENCY"), ("severe accident", "Emergency Medicine", "EMERGENCY"), ("poisoning", "Emergency Medicine", "EMERGENCY"), ("animal bite", "Emergency Medicine", "HIGH"),
]
