doctors_part3 = [

    {
        "doctor_name": "Dr. Chloe Adams",
        "email": "chloe.adams@medaqueue.com",
        "phone": "9876543233",
        "qualification": "MBBS, DM Endocrinology",
        "specialization": "Endocrinologist",
        "experience": 15,
        "consultation_fee": 850,
        "room_number": "EN-101",
        "available": True,
        "department": "Endocrinology",
    },

    {
        "doctor_name": "Dr. Harper Baker",
        "email": "harper.baker@medaqueue.com",
        "phone": "9876543234",
        "qualification": "MBBS, MD Radiology",
        "specialization": "Radiologist",
        "experience": 14,
        "consultation_fee": 800,
        "room_number": "RA-101",
        "available": True,
        "department": "Radiology",
    },

    {
        "doctor_name": "Dr. Samuel Carter",
        "email": "samuel.carter@medaqueue.com",
        "phone": "9876543235",
        "qualification": "MBBS, MD General Surgery",
        "specialization": "General Surgeon",
        "experience": 18,
        "consultation_fee": 900,
        "room_number": "GS-101",
        "available": True,
        "department": "General Surgery",
    },

    {
        "doctor_name": "Dr. Victoria Evans",
        "email": "victoria.evans@medaqueue.com",
        "phone": "9876543236",
        "qualification": "MBBS, MD Obstetrics",
        "specialization": "Obstetrician",
        "experience": 11,
        "consultation_fee": 850,
        "room_number": "OB-101",
        "available": True,
        "department": "Obstetrics",
    },

    {
        "doctor_name": "Dr. Daniel Brooks",
        "email": "daniel.brooks@medaqueue.com",
        "phone": "9876543237",
        "qualification": "MBBS, MS General Surgery",
        "specialization": "Laparoscopic Surgeon",
        "experience": 13,
        "consultation_fee": 1000,
        "room_number": "GS-102",
        "available": True,
        "department": "General Surgery",
    },

    {
        "doctor_name": "Dr. Natalie Cooper",
        "email": "natalie.cooper@medaqueue.com",
        "phone": "9876543238",
        "qualification": "MBBS, MD Pediatrics",
        "specialization": "Neonatal Specialist",
        "experience": 10,
        "consultation_fee": 800,
        "room_number": "P-103",
        "available": False,
        "department": "Pediatrics",
    },

    {
        "doctor_name": "Dr. Ryan Mitchell",
        "email": "ryan.mitchell@medaqueue.com",
        "phone": "9876543239",
        "qualification": "MBBS, DM Cardiology",
        "specialization": "Heart Failure Specialist",
        "experience": 16,
        "consultation_fee": 1100,
        "room_number": "C-103",
        "available": True,
        "department": "Cardiology",
    },

    {
        "doctor_name": "Dr. Sophie Bennett",
        "email": "sophie.bennett@medaqueue.com",
        "phone": "9876543240",
        "qualification": "MBBS, MS Orthopedics",
        "specialization": "Sports Injury Specialist",
        "experience": 12,
        "consultation_fee": 950,
        "room_number": "O-303",
        "available": True,
        "department": "Orthopedics",
    },

    {
        "doctor_name": "Dr. Jonathan Reed",
        "email": "jonathan.reed@medaqueue.com",
        "phone": "9876543241",
        "qualification": "MBBS, DM Neurology",
        "specialization": "Epilepsy Specialist",
        "experience": 17,
        "consultation_fee": 1100,
        "room_number": "N-203",
        "available": True,
        "department": "Neurology",
    },

    {
        "doctor_name": "Dr. Emma Foster",
        "email": "emma.foster@medaqueue.com",
        "phone": "9876543242",
        "qualification": "MBBS, MD Dermatology",
        "specialization": "Cosmetic Dermatologist",
        "experience": 9,
        "consultation_fee": 900,
        "room_number": "D-102",
        "available": True,
        "department": "Dermatology",
    },

]