doctors_part2 = [

    {
        "doctor_name": "Dr. Noah Walker",
        "email": "noah.walker@medaqueue.com",
        "phone": "9876543222",
        "qualification": "MBBS, MS ENT",
        "specialization": "ENT Surgeon",
        "experience": 12,
        "consultation_fee": 700,
        "room_number": "ENT-101",
        "available": True,
        "department": "ENT (Otolaryngology)",
    },

    {
        "doctor_name": "Dr. Isabella White",
        "email": "isabella.white@medaqueue.com",
        "phone": "9876543223",
        "qualification": "MBBS, MS Obstetrics & Gynecology",
        "specialization": "Gynecologist",
        "experience": 15,
        "consultation_fee": 850,
        "room_number": "GY-101",
        "available": True,
        "department": "Gynecology",
    },

    {
        "doctor_name": "Dr. Liam Scott",
        "email": "liam.scott@medaqueue.com",
        "phone": "9876543224",
        "qualification": "MBBS, MD Emergency Medicine",
        "specialization": "Emergency Physician",
        "experience": 11,
        "consultation_fee": 750,
        "room_number": "ER-101",
        "available": True,
        "department": "Emergency Medicine",
    },

    {
        "doctor_name": "Dr. Benjamin Lewis",
        "email": "benjamin.lewis@medaqueue.com",
        "phone": "9876543225",
        "qualification": "MBBS, MCh Urology",
        "specialization": "Urologist",
        "experience": 14,
        "consultation_fee": 900,
        "room_number": "U-101",
        "available": True,
        "department": "Urology",
    },

    {
        "doctor_name": "Dr. Henry King",
        "email": "henry.king@medaqueue.com",
        "phone": "9876543226",
        "qualification": "MBBS, DM Nephrology",
        "specialization": "Nephrologist",
        "experience": 13,
        "consultation_fee": 900,
        "room_number": "NE-101",
        "available": True,
        "department": "Nephrology",
    },

    {
        "doctor_name": "Dr. Lucas Hall",
        "email": "lucas.hall@medaqueue.com",
        "phone": "9876543227",
        "qualification": "MBBS, DM Oncology",
        "specialization": "Oncologist",
        "experience": 18,
        "consultation_fee": 1200,
        "room_number": "ON-101",
        "available": True,
        "department": "Oncology",
    },

    {
        "doctor_name": "Dr. Mason Allen",
        "email": "mason.allen@medaqueue.com",
        "phone": "9876543228",
        "qualification": "MBBS, DM Pulmonology",
        "specialization": "Pulmonologist",
        "experience": 12,
        "consultation_fee": 850,
        "room_number": "PU-101",
        "available": True,
        "department": "Pulmonology",
    },

    {
        "doctor_name": "Dr. Elijah Young",
        "email": "elijah.young@medaqueue.com",
        "phone": "9876543229",
        "qualification": "MBBS, DM Gastroenterology",
        "specialization": "Gastroenterologist",
        "experience": 16,
        "consultation_fee": 950,
        "room_number": "GI-101",
        "available": True,
        "department": "Gastroenterology",
    },

    {
        "doctor_name": "Dr. Grace Green",
        "email": "grace.green@medaqueue.com",
        "phone": "9876543230",
        "qualification": "MBBS, MD Psychiatry",
        "specialization": "Psychiatrist",
        "experience": 10,
        "consultation_fee": 700,
        "room_number": "PS-101",
        "available": True,
        "department": "Psychiatry",
    },

    {
        "doctor_name": "Dr. Amelia Roberts",
        "email": "amelia.roberts@medaqueue.com",
        "phone": "9876543231",
        "qualification": "MBBS, MD Emergency Medicine",
        "specialization": "Trauma Specialist",
        "experience": 9,
        "consultation_fee": 800,
        "room_number": "ER-102",
        "available": True,
        "department": "Emergency Medicine",
    },

    {
        "doctor_name": "Dr. Christopher Moore",
        "email": "christopher.moore@medaqueue.com",
        "phone": "9876543232",
        "qualification": "MBBS, MD General Medicine",
        "specialization": "Family Physician",
        "experience": 11,
        "consultation_fee": 650,
        "room_number": "GM-103",
        "available": True,
        "department": "General Medicine",
    },

]