doctors_part1 = [

    {
        "doctor_name": "Dr. Sarah Wilson",
        "email": "sarah.wilson@medaqueue.com",
        "phone": "9876543210",
        "qualification": "MBBS, DM Cardiology",
        "specialization": "Interventional Cardiologist",
        "experience": 12,
        "consultation_fee": 800,
        "room_number": "C-101",
        "available": True,
        "department": "Cardiology",
    },

    {
        "doctor_name": "Dr. James Anderson",
        "email": "james.anderson@medaqueue.com",
        "phone": "9876543211",
        "qualification": "MBBS, DM Cardiology",
        "specialization": "Cardiologist",
        "experience": 18,
        "consultation_fee": 1000,
        "room_number": "C-102",
        "available": True,
        "department": "Cardiology",
    },

    {
        "doctor_name": "Dr. Emily Davis",
        "email": "emily.davis@medaqueue.com",
        "phone": "9876543212",
        "qualification": "MBBS, DM Neurology",
        "specialization": "Neurologist",
        "experience": 15,
        "consultation_fee": 900,
        "room_number": "N-201",
        "available": True,
        "department": "Neurology",
    },

    {
        "doctor_name": "Dr. Robert Taylor",
        "email": "robert.taylor@medaqueue.com",
        "phone": "9876543213",
        "qualification": "MBBS, DM Neurology",
        "specialization": "Stroke Specialist",
        "experience": 10,
        "consultation_fee": 850,
        "room_number": "N-202",
        "available": True,
        "department": "Neurology",
    },

    {
        "doctor_name": "Dr. Michael Brown",
        "email": "michael.brown@medaqueue.com",
        "phone": "9876543214",
        "qualification": "MBBS, MS Orthopedics",
        "specialization": "Orthopedic Surgeon",
        "experience": 14,
        "consultation_fee": 850,
        "room_number": "O-301",
        "available": True,
        "department": "Orthopedics",
    },

    {
        "doctor_name": "Dr. David Harris",
        "email": "david.harris@medaqueue.com",
        "phone": "9876543215",
        "qualification": "MBBS, MS Orthopedics",
        "specialization": "Joint Replacement Specialist",
        "experience": 20,
        "consultation_fee": 1200,
        "room_number": "O-302",
        "available": True,
        "department": "Orthopedics",
    },

    {
        "doctor_name": "Dr. Sophia Taylor",
        "email": "sophia.taylor@medaqueue.com",
        "phone": "9876543216",
        "qualification": "MBBS, MD Pediatrics",
        "specialization": "Pediatrician",
        "experience": 9,
        "consultation_fee": 700,
        "room_number": "P-101",
        "available": True,
        "department": "Pediatrics",
    },

    {
        "doctor_name": "Dr. Olivia Martin",
        "email": "olivia.martin@medaqueue.com",
        "phone": "9876543217",
        "qualification": "MBBS, DCH",
        "specialization": "Child Specialist",
        "experience": 11,
        "consultation_fee": 750,
        "room_number": "P-102",
        "available": True,
        "department": "Pediatrics",
    },

    {
        "doctor_name": "Dr. Daniel Thomas",
        "email": "daniel.thomas@medaqueue.com",
        "phone": "9876543218",
        "qualification": "MBBS, MD General Medicine",
        "specialization": "Physician",
        "experience": 13,
        "consultation_fee": 600,
        "room_number": "GM-101",
        "available": True,
        "department": "General Medicine",
    },

    {
        "doctor_name": "Dr. William Clark",
        "email": "william.clark@medaqueue.com",
        "phone": "9876543219",
        "qualification": "MBBS, MD General Medicine",
        "specialization": "Internal Medicine",
        "experience": 17,
        "consultation_fee": 700,
        "room_number": "GM-102",
        "available": True,
        "department": "General Medicine",
    },

    {
        "doctor_name": "Dr. Ava Johnson",
        "email": "ava.johnson@medaqueue.com",
        "phone": "9876543220",
        "qualification": "MBBS, MD Dermatology",
        "specialization": "Dermatologist",
        "experience": 8,
        "consultation_fee": 700,
        "room_number": "D-101",
        "available": True,
        "department": "Dermatology",
    },

    {
        "doctor_name": "Dr. Ethan Harris",
        "email": "ethan.harris@medaqueue.com",
        "phone": "9876543221",
        "qualification": "MBBS, MS Ophthalmology",
        "specialization": "Eye Specialist",
        "experience": 16,
        "consultation_fee": 850,
        "room_number": "OP-101",
        "available": True,
        "department": "Ophthalmology",
    },

]