# Generated by Django 5.2.16 on 2026-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room_number', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.department')),
            ],
        ),
    ]
